#!/bin/bash
source ~/sample_tracking/CONFIG

mkdir -p ~/backups

now=`date +%Y%m%d%H%M%S`
mysqldump -u "$DATABASE_USER" "-p$DATABASE_PASSWORD" "$DATABASE_NAME" > ~/"backups/db_backup_$now.sql"

find ~/backups/ -mtime +30 -delete